
[workspace]
resolver = "2"
members = [
    "crates/spicy_circuit",
    "crates/spicy_errors",
    "crates/spicy_index",
    "crates/spicy_lang",
    "crates/spicy_model",
    "crates/spicy_netlist",
    "crates/spicy_simulate",
    "crates/spicy_span",
    "crates/spicy_cli",
    "fuzz",
]

[workspace.dependencies]
criterion = "0.8.1"

[profile.release]
debug = 2
