[package]
name = "spicy-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
spicy_netlist = {path = "../crates/spicy_netlist"}
spicy_lang = {path = "../crates/spicy_lang"}


[[bin]]
name = "fuzz_spicy_netlist"
path = "fuzz_targets/spicy_netlist.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_spicy_lang_lexer"
path = "fuzz_targets/spicy_lang_lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_spicy_lang_parser"
path = "fuzz_targets/spicy_lang_parser.rs"
test = false
doc = false
bench = false
